f = open('C:/anaconda3 for study/gitgit/uninstructed_robot-1/docs/md/junhea_workspace/practice_ch04/test.txt', 'r')
body = f.read()
f.close()
body = body.replace('java', 'python')
f = open('C:/anaconda3 for study/gitgit/uninstructed_robot-1/docs/md/junhea_workspace/practice_ch04/test.txt', 'w')
f.write(body)
f.close()